-- 코드를 입력하세요
SELECT 
    M.MEMBER_NAME, V.REVIEW_TEXT, DATE_FORMAT(V.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (SELECT
        MEMBER_ID, REVIEW_DATE, REVIEW_TEXT, COUNT(*) AS REVIEW_CNT 
      FROM REST_REVIEW 
      GROUP BY MEMBER_ID 
      ORDER BY REVIEW_CNT DESC
      LIMIT 1) R
INNER JOIN MEMBER_PROFILE M 
USING (MEMBER_ID)
INNER JOIN REST_REVIEW V
USING (MEMBER_ID)
ORDER BY V.REVIEW_DATE, V.REVIEW_TEXT
